defmodule ParrotSip.Auth.NonceStore do
  @moduledoc """
  GenServer for managing SIP authentication nonces with replay attack prevention.

  This module implements nonce generation, storage, and validation for SIP Digest
  authentication as specified in RFC 2617 and RFC 3261 Section 22.

  ## Features

  - Generates cryptographically secure nonces
  - Tracks nonce count (nc) for replay attack prevention
  - Supports nonce expiration with configurable TTL
  - Automatic cleanup of expired nonces
  - Returns `stale=true` for expired (but valid) nonces

  ## Usage

      # Start the store (usually in supervision tree)
      {:ok, pid} = NonceStore.start_link(name: MyApp.NonceStore)

      # Generate a nonce for a 401 challenge
      nonce = NonceStore.generate_nonce(pid)

      # Validate nonce and nc from Authorization header
      case NonceStore.validate_nonce(pid, nonce, nc) do
        :ok -> # Valid, proceed with authentication
        {:error, :invalid_nonce} -> # Unknown nonce, reject
        {:error, :stale_nonce} -> # Expired, send 401 with stale=true
        {:error, :replay_detected} -> # Replay attack, reject
      end

  ## RFC References

  - RFC 2617 Section 3.2.1: The WWW-Authenticate Response Header (nonce)
  - RFC 2617 Section 3.2.2: The Authorization Request Header (nc)
  - RFC 3261 Section 22: Usage of HTTP Authentication
  """

  use GenServer

  require Logger

  @default_ttl_seconds 300
  @default_cleanup_interval_ms 60_000

  # ============================================================================
  # Public API
  # ============================================================================

  @doc """
  Starts the NonceStore GenServer.

  ## Options

  - `:name` - GenServer name (default: `__MODULE__`)
  - `:ttl_seconds` - Nonce time-to-live in seconds (default: 300)
  - `:cleanup_interval` - Cleanup interval in milliseconds (default: 60000)

  ## Examples

      {:ok, pid} = NonceStore.start_link(name: :my_nonce_store)
      {:ok, pid} = NonceStore.start_link(ttl_seconds: 600)
  """
  def start_link(opts \\ []) do
    name = Keyword.get(opts, :name, __MODULE__)
    GenServer.start_link(__MODULE__, opts, name: name)
  end

  @doc """
  Generates a new nonce and stores it for later validation.

  The generated nonce is a cryptographically secure random string.
  It is stored with a timestamp for expiration tracking.

  ## Returns

  A binary string containing the nonce value.

  ## Examples

      nonce = NonceStore.generate_nonce(pid)
      # => "a8f5c4e9b2d1..."
  """
  @spec generate_nonce(GenServer.server()) :: String.t()
  def generate_nonce(server) do
    GenServer.call(server, :generate_nonce)
  end

  @doc """
  Validates a nonce and nonce count from an Authorization header.

  This function checks:
  1. The nonce was previously generated by this store
  2. The nonce has not expired
  3. The nonce count has not been used before (replay prevention)

  ## Parameters

  - `server` - The NonceStore server
  - `nonce` - The nonce value from the Authorization header
  - `nc` - The nonce count (nc) from the Authorization header, or nil if qop not used

  ## Returns

  - `:ok` - Nonce and nc are valid
  - `{:error, :invalid_nonce}` - Nonce was never generated or has been cleaned up
  - `{:error, :stale_nonce}` - Nonce has expired (client should retry with new nonce)
  - `{:error, :replay_detected}` - The nc value has already been used

  ## Examples

      :ok = NonceStore.validate_nonce(pid, nonce, "00000001")
      {:error, :stale_nonce} = NonceStore.validate_nonce(pid, old_nonce, "00000001")
  """
  @spec validate_nonce(GenServer.server(), String.t(), String.t() | nil) ::
          :ok | {:error, :invalid_nonce | :stale_nonce | :replay_detected}
  def validate_nonce(server, nonce, nc) do
    GenServer.call(server, {:validate_nonce, nonce, nc})
  end

  @doc """
  Invalidates a nonce, removing it from the store.

  Use this to immediately invalidate a nonce after successful authentication
  if you want single-use nonces.

  ## Examples

      :ok = NonceStore.invalidate_nonce(pid, nonce)
  """
  @spec invalidate_nonce(GenServer.server(), String.t()) :: :ok
  def invalidate_nonce(server, nonce) do
    GenServer.call(server, {:invalidate_nonce, nonce})
  end

  @doc """
  Gets information about a stored nonce.

  ## Returns

  - `{:ok, info}` - Map with `:created_at` and `:last_nc`
  - `{:error, :not_found}` - Nonce not in store

  ## Examples

      {:ok, %{created_at: ts, last_nc: 5}} = NonceStore.get_nonce_info(pid, nonce)
  """
  @spec get_nonce_info(GenServer.server(), String.t()) ::
          {:ok, %{created_at: integer(), last_nc: integer() | nil}} | {:error, :not_found}
  def get_nonce_info(server, nonce) do
    GenServer.call(server, {:get_nonce_info, nonce})
  end

  # ============================================================================
  # GenServer Callbacks
  # ============================================================================

  @impl true
  def init(opts) do
    ttl_seconds = Keyword.get(opts, :ttl_seconds, @default_ttl_seconds)
    cleanup_interval = Keyword.get(opts, :cleanup_interval, @default_cleanup_interval_ms)

    # Schedule periodic cleanup
    if cleanup_interval > 0 do
      Process.send_after(self(), :cleanup, cleanup_interval)
    end

    state = %{
      # %{nonce => %{created_at: timestamp, last_nc: integer | nil}}
      nonces: %{},
      ttl_seconds: ttl_seconds,
      cleanup_interval: cleanup_interval
    }

    {:ok, state}
  end

  @impl true
  def handle_call(:generate_nonce, _from, state) do
    nonce = generate_secure_nonce()
    now = System.system_time(:second)

    nonce_info = %{
      created_at: now,
      last_nc: nil
    }

    new_nonces = Map.put(state.nonces, nonce, nonce_info)

    {:reply, nonce, %{state | nonces: new_nonces}}
  end

  @impl true
  def handle_call({:validate_nonce, nonce, nc}, _from, state) do
    case Map.get(state.nonces, nonce) do
      nil ->
        {:reply, {:error, :invalid_nonce}, state}

      nonce_info ->
        now = System.system_time(:second)
        age = now - nonce_info.created_at

        cond do
          # Check if expired (>= because ttl_seconds is the max age)
          age >= state.ttl_seconds ->
            {:reply, {:error, :stale_nonce}, state}

          # No nc provided (qop not used) - just validate nonce existence
          nc == nil ->
            {:reply, :ok, state}

          # Check for replay
          true ->
            nc_int = parse_nc(nc)
            last_nc = nonce_info.last_nc || 0

            if nc_int > last_nc do
              # Valid - update last_nc
              updated_info = %{nonce_info | last_nc: nc_int}
              new_nonces = Map.put(state.nonces, nonce, updated_info)
              {:reply, :ok, %{state | nonces: new_nonces}}
            else
              # Replay detected - nc not greater than last used
              {:reply, {:error, :replay_detected}, state}
            end
        end
    end
  end

  @impl true
  def handle_call({:invalidate_nonce, nonce}, _from, state) do
    new_nonces = Map.delete(state.nonces, nonce)
    {:reply, :ok, %{state | nonces: new_nonces}}
  end

  @impl true
  def handle_call({:get_nonce_info, nonce}, _from, state) do
    case Map.get(state.nonces, nonce) do
      nil ->
        {:reply, {:error, :not_found}, state}

      info ->
        {:reply, {:ok, info}, state}
    end
  end

  @impl true
  def handle_info(:cleanup, state) do
    now = System.system_time(:second)
    cutoff = now - state.ttl_seconds

    # Remove expired nonces
    new_nonces =
      state.nonces
      |> Enum.reject(fn {_nonce, info} -> info.created_at < cutoff end)
      |> Map.new()

    removed_count = map_size(state.nonces) - map_size(new_nonces)

    if removed_count > 0 do
      Logger.debug("[NonceStore] Cleaned up #{removed_count} expired nonces")
    end

    # Schedule next cleanup
    if state.cleanup_interval > 0 do
      Process.send_after(self(), :cleanup, state.cleanup_interval)
    end

    {:noreply, %{state | nonces: new_nonces}}
  end

  # ============================================================================
  # Private Functions
  # ============================================================================

  defp generate_secure_nonce do
    # Generate timestamp-based nonce with random component
    # RFC 2617 Section 3.2.1: "The nonce is opaque to the client"
    timestamp = System.system_time(:second)
    random = :crypto.strong_rand_bytes(16) |> Base.encode16(case: :lower)

    "#{timestamp}:#{random}"
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  end

  defp parse_nc(nc) when is_binary(nc) do
    # nc is a hex string like "00000001"
    case Integer.parse(nc, 16) do
      {int, ""} -> int
      _ -> 0
    end
  end

  defp parse_nc(nc) when is_integer(nc), do: nc
  defp parse_nc(_), do: 0
end
